version: 0.2

env:
  variables:
    REGION: eu-north-1
    ACCOUNT_ID: 463932052716
    REGISTRY: 463932052716.dkr.ecr.eu-north-1.amazonaws.com
    BACKEND_IMAGE: my-first
    FRONTEND_IMAGE: k8s
    IMAGE_TAG: latest

phases:
  pre_build:
    commands:
      - echo "🔐 Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $REGISTRY

  build:
    commands:
      - echo "🛠️ Building Docker images..."
      - docker build -t $REGISTRY/$BACKEND_IMAGE:$IMAGE_TAG ./backend
      - docker build -t $REGISTRY/$FRONTEND_IMAGE:$IMAGE_TAG ./frontend

  post_build:
    commands:
      - echo "📤 Pushing images to ECR..."
      - docker push $REGISTRY/$BACKEND_IMAGE:$IMAGE_TAG
      - docker push $REGISTRY/$FRONTEND_IMAGE:$IMAGE_TAG
