version: 0.2

env:
  variables:
    REGION: us-east-1
    ACCOUNT_ID: 403135539729
    REGISTRY: 403135539729.dkr.ecr.us-east-1.amazonaws.com
    FRONTEND_IMAGE: ttt-frontend
    BACKEND_IMAGE: ttt-backend

phases:
  pre_build:
    commands:
      - echo "🔐 Logging into ECR..."
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $REGISTRY

  build:
    commands:
      - echo "⚙️ Building backend and frontend Docker images..."
      - docker compose build
      - docker tag $BACKEND_IMAGE:latest $REGISTRY/$BACKEND_IMAGE:latest
      - docker tag $FRONTEND_IMAGE:latest $REGISTRY/$FRONTEND_IMAGE:latest

  post_build:
    commands:
      - echo "📤 Pushing Docker images to ECR..."
      - docker push $REGISTRY/$BACKEND_IMAGE:latest
      - docker push $REGISTRY/$FRONTEND_IMAGE:latest

      - echo "📁 Zipping for CodeDeploy..."
      - mkdir -p codedeploy/scripts
      - cp appspec.yml codedeploy/
      - cp scripts/deploy.sh codedeploy/scripts/
      - cd codedeploy
      - zip -r ../build.zip ./

artifacts:
  files:
    - build.zip

