version: 0.2

env:
  variables:
    REGION: us-east-1
    ACCOUNT_ID: 463932052716
    REGISTRY: 463932052716.dkr.ecr.eu-north-1.amazonaws.com/my-first
    BACKEND_IMAGE: my-first      # ✅ Backend to cicd repo
    FRONTEND_IMAGE: k8s      # ✅ Frontend to ttt repo

phases:
  pre_build:
    commands:
      - echo "🔐 Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $REGISTRY
      - echo "✅ Login complete"

  build:
    commands:
      - echo "🛠️ Building Docker images..."
      - docker build -t $REGISTRY/$BACKEND_IMAGE:latest ./backend
      - docker build -t $REGISTRY/$FRONTEND_IMAGE:latest ./frontend

  post_build:
    commands:
      - echo "📤 Pushing images to ECR..."
      - docker push $REGISTRY/$BACKEND_IMAGE:latest
      - docker push $REGISTRY/$FRONTEND_IMAGE:latest

      - echo "📦 Creating CodeDeploy bundle..."
      - mkdir -p codedeploy/scripts
      - cp appspec.yml codedeploy/
      - cp scripts/deploy.sh codedeploy/scripts/
      - cd codedeploy
      - zip -r ../build.zip ./

artifacts:
  files:
    - build.zip 
