version: 0.2

env:
  variables:
    REGION: eu-north-1
    ACCOUNT_ID: 463932052716
    REGISTRY: 463932052716.dkr.ecr.eu-north-1.amazonaws.com
    BACKEND_IMAGE: my-first
    IMAGE_TAG: latest

phases:
  pre_build:
    commands:
      - echo "ðŸ”‘ Logging in to Amazon ECR..."
      - aws --version
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $REGISTRY
      - echo "âœ… Logged in to ECR"

  build:
    commands:
      - echo "ðŸ³ Building Docker image..."
      - docker build -t $REGISTRY/$BACKEND_IMAGE:$IMAGE_TAG .
      - echo "âœ… Docker build complete"

  post_build:
    commands:
      - echo "ðŸ“¤ Pushing Docker image to ECR..."
      - echo "DEBUG => $REGISTRY/$BACKEND_IMAGE:$IMAGE_TAG"
      - docker push $REGISTRY/$BACKEND_IMAGE:$IMAGE_TAG
      - echo "âœ… Image pushed successfully"

artifacts:
  files:
    - '**/*'

